### ISSUE TITLE
Todo v2

### ISSUE THREAD

**Issue by martinbroos** [freshheads/maatcss#62]
- [x]  svg-uri heeft nog een warning -> url encoden zou voldoende moeten zijn en niet meer omzetten naar base64 (https://css-tricks.com/probably-dont-base64-svg/)
- [x] dev dependencies upgraden
- [x] sass-mq v6 stable version
- [x]  break changes noteren in upgrade guide

Deze release zou niet al teveel impact moeten hebben. Voor de v3 willen we eens opnieuw gaan kijken naar hoe we maat.css beter kunnen laten inspelen op css modules die nu vaak gebruikt worden. Wellicht het wat minder gaan zien als een start punt van je project maar meer als een library met css modules. Word vervolgd.

**Comment by martinbroos** [comment]
Besloten om in v2 niet te upgraden naar webpack 5.
Wel zijn de bestaande punten opgepakt om dart-sass warnings op te lossen.

Op dit moment hebben we het voornemen om geen v3 meer te maken die toegespitst is op css modules. We denken dat de meerwaarde beter te vinden is in UI frameworks zoals Radix UI en Chakra UI die beter aansluiten op de react stack die we nu hanteren.

We zullen we het nodige onderhoud op v2 blijven doen. En mochten daar breaking changes uit naar voren komen kan dat vanzelfsprekend wel in een v3 release.
